### ISSUE TITLE
Error bot

### ISSUE THREAD

**Issue by ghost** [Dryrtan/Spotify-Download-Telegram-Bot#2]
Olá amigo, estou com este erro. o bot não funciona, em qual versão do python você o executa?
![image](https://user-images.githubusercontent.com/31140793/128108148-20e77e2d-a403-4ae7-90f5-88f73840db85.png)

**Comment by Dryrtan** [comment]
Olá amigo, uso o python3 para executar, indico usar no Linux pois existe alguns comandos que são especifico para ele.
Eu indico um server AWS, é só colocar pra rodar e deixar funcionado em nuvem.

**Comment by ghost** [comment]
O erro me parece estranho, tentarei consertá-lo. Eu queria que ele rodasse no Heroku (linux) e no windows e nada ..

**Comment by Dryrtan** [comment]
Poderia me mandar a saida completa desse erro?

**Comment by ghost** [comment]
```
2021-08-04T16:15:21.610327+00:00 heroku[worker.1]: Starting process with command `python3 spotify-bot.py`
2021-08-04T16:15:22.347510+00:00 heroku[worker.1]: State changed from starting to up
2021-08-04T16:15:27.221979+00:00 heroku[worker.1]: Process exited with status 1
2021-08-04T16:15:27.307438+00:00 heroku[worker.1]: State changed from up to crashed
2021-08-04T16:15:27.312245+00:00 heroku[worker.1]: State changed from crashed to starting
2021-08-04T16:15:27.129980+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-04T16:15:27.130005+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 104, in <module>
2021-08-04T16:15:27.130285+00:00 app[worker.1]:     Bot.Iniciar()
2021-08-04T16:15:27.130316+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 31, in Iniciar
2021-08-04T16:15:27.130533+00:00 app[worker.1]:     resposta = self.criar_resposta(
2021-08-04T16:15:27.130562+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 55, in criar_resposta
2021-08-04T16:15:27.130824+00:00 app[worker.1]:     upload.sms(self.ids, 'Estamos baixando sua musica, agorinha enviamos.')
2021-08-04T16:15:27.130852+00:00 app[worker.1]:   File "/app/upload.py", line 27, in sms
2021-08-04T16:15:27.131149+00:00 app[worker.1]:     bot.send_message(chat_id=chat_id, text=sms)
2021-08-04T16:15:27.131194+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
2021-08-04T16:15:27.131445+00:00 app[worker.1]:     result = func(*args, **kwargs)
2021-08-04T16:15:27.131473+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 513, in send_message
2021-08-04T16:15:27.134769+00:00 app[worker.1]:     return self._message(  # type: ignore[return-value]
2021-08-04T16:15:27.134799+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 332, in _message
2021-08-04T16:15:27.135123+00:00 app[worker.1]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2021-08-04T16:15:27.135151+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
2021-08-04T16:15:27.135458+00:00 app[worker.1]:     return self.request.post(
2021-08-04T16:15:27.135487+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/utils/request.py", line 356, in post
2021-08-04T16:15:27.135816+00:00 app[worker.1]:     result = self._request_wrapper(
2021-08-04T16:15:27.135844+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
2021-08-04T16:15:27.136143+00:00 app[worker.1]:     raise Unauthorized(message)
2021-08-04T16:15:27.136290+00:00 app[worker.1]: telegram.error.Unauthorized: Forbidden: bot was blocked by the user
2021-08-04T16:15:38.120733+00:00 heroku[worker.1]: Starting process with command `python3 spotify-bot.py`
2021-08-04T16:15:38.922540+00:00 heroku[worker.1]: State changed from starting to up
2021-08-04T16:15:42.509356+00:00 heroku[worker.1]: Process exited with status 1
2021-08-04T16:15:42.654809+00:00 heroku[worker.1]: State changed from up to crashed
2021-08-04T16:15:42.425285+00:00 app[worker.1]: Traceback (most recent call last):
2021-08-04T16:15:42.425325+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 104, in <module>
2021-08-04T16:15:42.425504+00:00 app[worker.1]:     Bot.Iniciar()
2021-08-04T16:15:42.425506+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 31, in Iniciar
2021-08-04T16:15:42.425643+00:00 app[worker.1]:     resposta = self.criar_resposta(
2021-08-04T16:15:42.425647+00:00 app[worker.1]:   File "/app/spotify-bot.py", line 55, in criar_resposta
2021-08-04T16:15:42.425822+00:00 app[worker.1]:     upload.sms(self.ids, 'Estamos baixando sua musica, agorinha enviamos.')
2021-08-04T16:15:42.425827+00:00 app[worker.1]:   File "/app/upload.py", line 27, in sms
2021-08-04T16:15:42.425958+00:00 app[worker.1]:     bot.send_message(chat_id=chat_id, text=sms)
2021-08-04T16:15:42.425962+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
2021-08-04T16:15:42.426133+00:00 app[worker.1]:     result = func(*args, **kwargs)
2021-08-04T16:15:42.426137+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 513, in send_message
2021-08-04T16:15:42.426382+00:00 app[worker.1]:     return self._message(  # type: ignore[return-value]
2021-08-04T16:15:42.426396+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 332, in _message
2021-08-04T16:15:42.426593+00:00 app[worker.1]:     result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
2021-08-04T16:15:42.426597+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
2021-08-04T16:15:42.426801+00:00 app[worker.1]:     return self.request.post(
2021-08-04T16:15:42.426802+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/utils/request.py", line 356, in post
2021-08-04T16:15:42.427000+00:00 app[worker.1]:     result = self._request_wrapper(
2021-08-04T16:15:42.427017+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/telegram/utils/request.py", line 277, in _request_wrapper
2021-08-04T16:15:42.427198+00:00 app[worker.1]:     raise Unauthorized(message)
2021-08-04T16:15:42.427282+00:00 app[worker.1]: telegram.error.Unauthorized: Forbidden: bot was blocked by the user
```

**Comment by Dryrtan** [comment]
Hoje vou fazer um conteiner Docker com a aplicação dentro com a aplicação em funcionamento.

**Comment by CALO77103** [comment]
That means u or somehow blocked the bot, unblock in telegram and it should work
